import './globals.css'
import Nav from './nav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='h-screen w-full text-white bg-red-500 flex flex-col sm:flex-row'>
        <Nav />
        {children}
      </body>
    </html>
  );
}
